config/routes.rb
Rails.application.routes.draw do

  resources :orders, only: [:create,:show,:index] do 
    post :add_to_cart, on: :collection
  end

  get :cart, controller: :orders

  resources :profile, only: [:index, :update, :delete]
  devise_for :users, controllers: {registrations:'users/registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"

  resources :products, only: [:index, :show]

  scope :admin do 
    resources :products, controller: :product_admins , as: :product_admins
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/admin.rb
class Admin < User
    def is_admin 
        true
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/client.rb
class Client < User
    has_one :order, foreign_key: :user_id

    def is_client
        true
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :address, required: false
  has_many :order_products
  enum state:{progress:"P", completed:"C"}

  validates :user_id, presence: true, if: -> {is_cart?}
  validates :address, presence: true, unless: -> {is_cart?}
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    has_many_attached :images
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  include Discard::Model

  def is_admin 
    false
  end
  def is_client
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def admin_only
        unless current_user&.is_admin
            flash[:alert] = "Esta de vivo #{current_user&.email}"
            redirect_to root_path 
        end
    end
    def client_only
        unless current_user&.is_client
            flash[:alert] = "Esta de vivo #{current_user&.email}"
            redirect_to root_path 
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
  end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


  def index
  end

  def show
  end

  def create
  end

  def add_to_cart

    if current_user
    @order = get_cart_order
    current_product = order_product_params
    totalAmount = current_product[:quantity].to_i * current_product[:unit_price].to_i
    update_order = @order.update(totalAmount:totalAmount + @order.totalAmount)
    @order_product = find_or_update_order_product(@order, current_product)
    


    if update_order && @order_product.save
      redirect_to cart_url
    else
    redirect_back fallback_location: products_path
    end
  else
    redirect_to new_user_session_url, alert: 'Tienes que registrarte primero'
  end
  end

  def cart 
    @cart = get_cart_order
    puts @cart.inspect
  end

  private
  def get_cart_order 
    @current_order = current_user.order
    if @current_order.nil?
      @current_order = Order.create(user_id: current_user.id, state: :progress, totalAmount: 0 , is_cart: true)
    end
    @current_order
  end
  def find_or_update_order_product (order, order_product)
    @order_product = order.order_products.find_by(product_id:order_product[:product_id])
    if @order_product.nil?
      @order_product = OrderProduct.new(order_product.merge(order_id: order.id))
    else
      puts 'ACA',@order_product
      @order_product.quantity += order_product[:quantity].to_i
    end
    @order_product
  end
  def order_product_params
    params.fetch(:order_product, {}).permit(:quantity, :product_id, :unit_price)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @order_product = OrderProduct.new()
  end
  
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!
  before_action :client_only

  def index
  end

  def update
    if current_user.update(profile_params)
      flash['notice'] = 'Perfil actualizado correctamente'
      redirect_to profile_index_path
    else
      flash['alert'] = 'Hubo un error al actualizar perfil'
      render 'index'
    end
  end

  def delete
  end
  
  private
  def profile_params
    params.fetch(:client, {}).permit(:name, :age, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def user_is_admin?
        user_signed_in? && current_user.is_admin
    end
    def user_is_client?
        user_signed_in? && current_user.is_client
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_admins_helper.rb
module ProductAdminsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>ECommerce</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%=render "partials/nav" %>
        <% if notice%>
      <p class="alert alert-primary"><%= notice %></p>
    <%end%>
    <% if alert%>
      <p class="alert alert-danger"><%= alert %></p>
    <%end%>
    <%= yield %>
</body>
</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <ul class="nav">
        <li class="nav-item">
            <%= link_to "Productos", products_url, class:"nav-link" %>
        </li>
        <% if user_is_admin? %>
        <li class="nav-item">
            <%= link_to "Admin", product_admins_url, class:"nav-link" %>
        </li>
        <%end %>
        <% if user_is_client? %>
        <li class="nav-item">
            <%= link_to "Perfil", profile_index_path, class:"nav-link" %>
        </li>
        <%end%>
        <% if user_is_admin? %>
        <li class="nav-item">
            <%= link_to "Config Account", edit_user_registration_path, class:"nav-link" %>
        </li>
        <%end%>
        <% if user_signed_in?%>
        <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, class:"nav-link", method: :delete%>
        </li>
        <%else%>
            <%= link_to "Login", new_user_session_url, class:"nav-link"%>
            <%= link_to "Sign up", new_user_registration_url, class:"nav-link"%>
        <%end%>
    </ul>
</nav>