config/routes.rb
Rails.application.routes.draw do

  resources :orders, only: [:create,:show,:index] do 
    post :add_to_cart, on: :collection
  end

  get :cart, controller: :orders

  resources :profile, only: [:index, :update, :delete]
  devise_for :users, controllers: {registrations:'users/registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"

  resources :products, only: [:index, :show]

  scope :admin do 
    resources :products, controller: :product_admins , as: :product_admins
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/admin.rb
class Admin < User
    def is_admin 
        true
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/client.rb
class Client < User
    has_one :order, foreign_key: :user_id

    def is_client
        true
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :address, required: false
  has_many :order_products
  enum state:{progress:"P", completed:"C"}

  validates :user_id, presence: true, if: -> {is_cart?}
  validates :address, presence: true, unless: -> {is_cart?}
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    has_many_attached :images
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  include Discard::Model

  def is_admin 
    false
  end
  def is_client
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def admin_only
        unless current_user&.is_admin
            flash[:alert] = "Esta de vivo #{current_user&.email}"
            redirect_to root_path 
        end
    end
    def client_only
        unless current_user&.is_client
            flash[:alert] = "Esta de vivo #{current_user&.email}"
            redirect_to root_path 
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
  end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


  def index
  end

  def show
  end

  def create
  end

  def add_to_cart

    if current_user
    @order = get_cart_order
    current_product = order_product_params
    totalAmount = current_product[:quantity].to_i * current_product[:unit_price].to_i
    update_order = @order.update(totalAmount:totalAmount + @order.totalAmount)
    @order_product = find_or_update_order_product(@order, current_product)
    


    if update_order && @order_product.save
      redirect_to cart_url
    else
    redirect_back fallback_location: products_path
    end
  else
    redirect_to new_user_session_url, alert: 'Tienes que registrarte primero'
  end
  end

  def cart 
    @cart = get_cart_order
    puts @cart.inspect
  end

  private
  def get_cart_order 
    @current_order = current_user.order
    if @current_order.nil?
      @current_order = Order.create(user_id: current_user.id, state: :progress, totalAmount: 0 , is_cart: true)
    end
    @current_order
  end
  def find_or_update_order_product (order, order_product)
    @order_product = order.order_products.find_by(product_id:order_product[:product_id])
    if @order_product.nil?
      @order_product = OrderProduct.new(order_product.merge(order_id: order.id))
    else
      puts 'ACA',@order_product
      @order_product.quantity += order_product[:quantity].to_i
    end
    @order_product
  end
  def order_product_params
    params.fetch(:order_product, {}).permit(:quantity, :product_id, :unit_price)
  end
end

app/controllers/product_admins_controller.rb
class ProductAdminsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user!
  before_action :admin_only


  # GET /product_admins or /product_admins.json
  def index
    @product_admins = Product.all
  end

  # GET /product_admins/1 or /product_admins/1.json
  def show
  end

  # GET /product_admins/new
  def new
    @product_admin = Product.new
  end

  # GET /product_admins/1/edit
  def edit
  end

  # POST /product_admins or /product_admins.json
  def create
    @product_admin = Product.new(product_params)

    respond_to do |format|
      if @product_admin.save
        format.html { redirect_to @product_admin, notice: "Product admin was successfully created." }
        format.json { render :show, status: :created, location: @product_admin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_admins/1 or /product_admins/1.json
  def update
    respond_to do |format|
      if @product_admin.update(product_params)
        format.html { redirect_to @product_admin, notice: "Product admin was successfully updated." }
        format.json { render :show, status: :ok, location: @product_admin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_admins/1 or /product_admins/1.json
  def destroy
    @product_admin.destroy
    respond_to do |format|
      format.html { redirect_to product_admins_url, notice: "Product admin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product_admin = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.fetch(:product, {}).permit(:name, :description, :price, :sale_price, :quantity, :image, images:[])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @order_product = OrderProduct.new()
  end
  
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!
  before_action :client_only

  def index
  end

  def update
    if current_user.update(profile_params)
      flash['notice'] = 'Perfil actualizado correctamente'
      redirect_to profile_index_path
    else
      flash['alert'] = 'Hubo un error al actualizar perfil'
      render 'index'
    end
  end

  def delete
  end
  
  private
  def profile_params
    params.fetch(:client, {}).permit(:name, :age, :email)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def user_is_admin?
        user_signed_in? && current_user.is_admin
    end
    def user_is_client?
        user_signed_in? && current_user.is_client
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_admins_helper.rb
module ProductAdminsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/product_admins/_form.html.erb
<%= form_with(model: product_admin, url: is_new ? product_admins_path(product_admin) : product_admin_path(product_admin)) do |form| %>
<% if product_admin.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(product_admin.errors.count, "error") %> prohibited this product_admin from being saved:</h2>
    <ul>
        <% product_admin.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="actions">
    <div class="field">
        <%=form.label :name %>
        <%=form.text_field :name %>
        <% @product_admin.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>
    <div class="field">
        <%=form.label :description %>
        <%=form.text_field :description %>
        <% @product_admin.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>
    <div class="field">
        <%=form.label :price %>
        <%=form.number_field :price %>
        <% @product_admin.errors.full_messages_for(:price).each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>
    <div class="field">
        <%=form.label :sale_price %>
        <%=form.number_field :sale_price %>
        <% @product_admin.errors.full_messages_for(:sale_price).each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>
    <div class="field">
        <%=form.label :quantity %>
        <%=form.number_field :quantity %>
        <% @product_admin.errors.full_messages_for(:quantity).each do |message| %>
        <div><%= message %></div>
        <% end %>
    </div>
    <div class="field">
        <%=form.label :image %>
        <%=form.file_field :image,  accept: "image/*" %>
        <% @product_admin.errors.full_messages_for(:image).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div class="field">
        <%=form.label :images %>
        <%=form.file_field :images,  accept: "image/*", multiple:true %>
        <% @product_admin.errors.full_messages_for(:images).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div class="field">
        <%= form.submit %>
    </div>
</div>
<% end %>

app/views/product_admins/edit.html.erb
<div class="container">
    <%= link_to product_admins_path do %>
    <i class="bi bi-arrow-left-circle-fill"></i>
    <% end %>
    <h1>Editing Product Admin</h1>
    <%= render 'form', product_admin: @product_admin, is_new:false %>

</div>

app/views/product_admins/index.html.erb
<h1>Product Admins</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_admins.each do |product_admin| %>
      <tr>
        <td><%= link_to 'Show', product_admin %></td>
        <td><%= link_to 'Edit', edit_product_admin_path(product_admin) %></td>
        <td><%= link_to 'Destroy', product_admin_path(product_admin), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Admin', new_product_admin_path %>

app/views/product_admins/new.html.erb
<div class="container">
    <h1>New Product Admin</h1>
    <%= render 'form', product_admin: @product_admin, is_new:true %>
    <%= link_to 'Back', product_admins_path %>
</div>

app/views/product_admins/show.html.erb
<%= link_to 'Edit', edit_product_admin_path(@product_admin) %> |
<%= link_to 'Back', product_admins_path %>