config/routes.rb
Rails.application.routes.draw do

  resources :orders, only: [:create,:show,:index] do 
    post :add_to_cart, on: :collection
  end

  get :cart, controller: :orders

  resources :profile, only: [:index, :update, :delete]
  devise_for :users, controllers: {registrations:'users/registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "products#index"

  resources :products, only: [:index, :show]

  scope :admin do 
    resources :products, controller: :product_admins , as: :product_admins
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/admin.rb
class Admin < User
    def is_admin 
        true
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/client.rb
class Client < User
    has_one :order, foreign_key: :user_id

    def is_client
        true
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :address, required: false
  has_many :order_products
  enum state:{progress:"P", completed:"C"}

  validates :user_id, presence: true, if: -> {is_cart?}
  validates :address, presence: true, unless: -> {is_cart?}
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
    has_one_attached :image
    has_many_attached :images
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  include Discard::Model

  def is_admin 
    false
  end
  def is_client
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def admin_only
        unless current_user&.is_admin
            flash[:alert] = "Esta de vivo #{current_user&.email}"
            redirect_to root_path 
        end
    end
    def client_only
        unless current_user&.is_client
            flash[:alert] = "Esta de vivo #{current_user&.email}"
            redirect_to root_path 
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
  end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController


  def index
  end

  def show
  end

  def create
  end

  def add_to_cart

    if current_user
    @order = get_cart_order
    current_product = order_product_params
    totalAmount = current_product[:quantity].to_i * current_product[:unit_price].to_i
    update_order = @order.update(totalAmount:totalAmount + @order.totalAmount)
    @order_product = find_or_update_order_product(@order, current_product)
    


    if update_order && @order_product.save
      redirect_to cart_url
    else
    redirect_back fallback_location: products_path
    end
  else
    redirect_to new_user_session_url, alert: 'Tienes que registrarte primero'
  end
  end

  def cart 
    @cart = get_cart_order
    puts @cart.inspect
  end

  private
  def get_cart_order 
    @current_order = current_user.order
    if @current_order.nil?
      @current_order = Order.create(user_id: current_user.id, state: :progress, totalAmount: 0 , is_cart: true)
    end
    @current_order
  end
  def find_or_update_order_product (order, order_product)
    @order_product = order.order_products.find_by(product_id:order_product[:product_id])
    if @order_product.nil?
      @order_product = OrderProduct.new(order_product.merge(order_id: order.id))
    else
      puts 'ACA',@order_product
      @order_product.quantity += order_product[:quantity].to_i
    end
    @order_product
  end
  def order_product_params
    params.fetch(:order_product, {}).permit(:quantity, :product_id, :unit_price)
  end
end

app/controllers/product_admins_controller.rb
class ProductAdminsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user!
  before_action :admin_only


  # GET /product_admins or /product_admins.json
  def index
    @product_admins = Product.all
  end

  # GET /product_admins/1 or /product_admins/1.json
  def show
  end

  # GET /product_admins/new
  def new
    @product_admin = Product.new
  end

  # GET /product_admins/1/edit
  def edit
  end

  # POST /product_admins or /product_admins.json
  def create
    @product_admin = Product.new(product_params)

    respond_to do |format|
      if @product_admin.save
        format.html { redirect_to @product_admin, notice: "Product admin was successfully created." }
        format.json { render :show, status: :created, location: @product_admin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_admins/1 or /product_admins/1.json
  def update
    respond_to do |format|
      if @product_admin.update(product_params)
        format.html { redirect_to @product_admin, notice: "Product admin was successfully updated." }
        format.json { render :show, status: :ok, location: @product_admin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product_admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_admins/1 or /product_admins/1.json
  def destroy
    @product_admin.destroy
    respond_to do |format|
      format.html { redirect_to product_admins_url, notice: "Product admin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product_admin = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.fetch(:product, {}).permit(:name, :description, :price, :sale_price, :quantity, :image, images:[])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @order_product = OrderProduct.new()
  end
  
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!
  before_action :client_only

  def index
  end

  def update
    if current_user.update(profile_params)
      flash['notice'] = 'Perfil actualizado correctamente'
      redirect_to profile_index_path
    else
      flash['alert'] = 'Hubo un error al actualizar perfil'
      render 'index'
    end
  end

  def delete
  end
  
  private
  def profile_params
    params.fetch(:client, {}).permit(:name, :age, :email)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def user_is_admin?
        user_signed_in? && current_user.is_admin
    end
    def user_is_client?
        user_signed_in? && current_user.is_client
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_admins_helper.rb
module ProductAdminsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/orders/cart.html.erb
<h1>Carrito</h1>
<% @cart.order_products.each do |item| %>
<p> <%=render item %> </p>
<p> <%=item.quantity %></p>
<%end%>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/products/_product.html.erb
<div class="col mb-2">
    <div class="card" style="width: 18rem;">
    <%if product.image.attached? %>
        <%=image_tag product.image, class:"card-img-top"  %>
    <%else%>
        <img src="https://cdn.pixabay.com/photo/2016/11/19/18/06/feet-1840619_1280.jpg" alt="...">
    <%end%>
        <div class="card-body">
            <h5 class="card-title"><%= product.name %></h5>
            <p class="card-text"><%= product.description %></p>
            <%= link_to "Ver producto", product, class:"btn btn-primary" %>
        </div>
    </div>
</div>

app/views/products/index.html.erb
<div class="container">
    <h1>Productos</h1>
    <div class="row align-items-start">
        <%= render @products %>
    </div>
</div>

app/views/products/show.html.erb
<div class="container mt-3">
    <div class="row">
        <div class="col-7">
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0"
                        class="active" aria-current="true" aria-label="Slide 1"></button>
                    <% @product.images.length.times do |index| %>
                        <button type="button" data-bs-target="#carouselExampleIndicators"
                            data-bs-slide-to="<%=index+1%>" aria-label="Slide <%=index%>"></button>
                        <%end%>
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <%if @product.image.attached? %>
                            <%=image_tag @product.image, class:"d-block w-100" %>
                                <%else%>
                                    <img src="https://cdn.pixabay.com/photo/2016/11/19/18/06/feet-1840619_1280.jpg"
                                        alt="..." class="d-block w-100">
                                    <%end%>
                    </div>
                    <%if @product.images.attached? %>
                        <% @product.images.each do |item| %>
                            <div class="carousel-item">
                                <%=image_tag item, class:"d-block w-100" %>
                            </div>
                            <%end%>
                                <%end%>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
        <div class="col">
            <h1 class="display-3 font-weight-bold">
                <%=@product.name %>
            </h1>
            <p class="h4 fw-normal text-muted">
                <%= @product.description %>
            </p>
            <% if(@product.sale_price) %>
                <p class="h2 text-decoration-line-through fw-normal">Precio Original: $<%= @product.price %> </span>
                        <p class="h2 fw-normal">Oferta: <span class="text-danger">$<%= @product.sale_price %></span>
                            <%else %>
                                <p class="h2 fw-normal">Precio: $<%= @product.price %> </span>
                                        <%end %>
                                            <p class="h2 fw-normal">Stock: <%= @product.quantity %>
                                            </p>
                                            <%= form_with model: @order_product, url: add_to_cart_orders_path,
                                                remote:false do |form| %>
                                                <div class="mb-3">
                                                    <%=form.label :quantity, "Cantidad" %>
                                                        <%=form.number_field :quantity, placeholder:"1",
                                                            class:"form-control", min:1 %>
                                                        <%=form.hidden_field :product_id, value:@product.id,
                                                            class:"form-control" %>
                                                        <%=form.hidden_field :unit_price, value:@product.sale_price || @product.price,
                                                            class:"form-control"%>                                                            
                                                </div>
                                                <div class="form-check form-switch mb-3">
                                                    <input class="form-check-input" type="checkbox"
                                                        id="flexSwitchCheckDefault">
                                                    <label class="form-check-label" for="flexSwitchCheckDefault">Envío
                                                        incluido</label>
                                                </div>
                                                <button type="submit" class="btn btn-primary"><i class="bi bi-cart"></i>
                                                    Agregar al carrito </button>
                                                <%# <button type="submit" class="btn btn-success w-20"><i
                                                        class="bi bi-whatsapp"></i> Contactarse </button> %>
                                                <%end%>
        </div>
    </div>
</div>